pruebas_index:
  path: /pruebas/{lang}/{name}/{page}
  defaults: { _controller: AppBundle:Pruebas:index, lang:es, page:1 }
  methods: [GET, POST]
  requirements:
    name: "[a-zA-Z]*"
    page: \d+
    lang: es|eng|fr