pruebas_index:
  path: /pruebas/{lang}/{name}/{page}
  defaults: { _controller: AppBundle:Pruebas:index, lang:es, page:1 }
  methods: [GET]
  requirements:
    name: \w+
    page: \d+
    lang: es|eng|fr