AppBundle\Entity\Curso:
  properties:
    titulo:
      - NotBlank: {message: "El título no puede estar vacío"}
      - Length:
        min: 2
        minMessage: "El título debe tener más de 2 caracteres"
    descripcion:
      - NotBlank: {message: "La descripción no puede estar vacía"}
    precio:
      - Type:
        type: digit
        message: "El precio tiene que ser numérico"

